CREATE TABLE IF NOT EXISTS rates (
  id TINYINT UNSIGNED NOT NULL DEFAULT 1,
  gold_24 DECIMAL(10,2) NOT NULL CHECK (gold_24 > 0),
  gold_22 DECIMAL(10,2) NOT NULL CHECK (gold_22 > 0),
  gold_18 DECIMAL(10,2) NOT NULL CHECK (gold_18 > 0),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT rates_single_row CHECK (id = 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
